services:
  postgres:
    image: postgres:16-alpine
    container_name: service-provider-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: marcae
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: service-provider-pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
      PGPASS_FILE: /config/pgpass
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./infra/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./infra/pgadmin/pgpass:/config/pgpass:ro

volumes:
  postgres-data:
  pgadmin-data:
